/**
 * Editorial intro paragraphs for brand pages.
 * Keyed by the exact brand name as it appears in the CSV.
 */
export const BRAND_INTROS: Record<string, string> = {
  Skywalker:
    "Skywalker Trampolines is a US brand founded in 2005 and based in Brigham City, Utah, owned by Skywalker Holdings. The brand sells a wide range of round, rectangular, square, and oval trampolines from 7ft up to 16ft, plus a Mini line for younger kids and indoor mini fitness trampolines. Models are organized into Classic, Signature, Epic, and Premium series, typically priced from around $200 to $900, and are sold at Walmart, Amazon, Target, Academy Sports, Dick's Sporting Goods, and Sam's Club. Skywalker is known for its patented no-gap enclosure design, where the safety net attaches directly to the jump mat. It is one of the highest-volume mass-market trampoline brands in the US.",

  'Little Tikes':
    "Little Tikes is a long-established US toy brand best known for plastic outdoor play equipment for toddlers and young kids. Its trampoline lineup focuses on the kids and toddler segment, with models ranging from compact 3ft indoor trampolines with handlebars to 7ft outdoor models with safety nets and Mega outdoor models in 12ft and 15ft sizes. Indoor models typically have weight limits around 55 lb and are designed for ages 3 to 6, while the larger outdoor models support up to 220 lb. Pricing ranges from around $40 for indoor mini trampolines to a few hundred dollars for the Mega outdoor sizes, and the trampolines are sold through Little Tikes' own site, Walmart, Target, Amazon, and other big-box retailers.",

  'Sportspower / Bounce Pro':
    "Sportspower Ltd is a manufacturer and distributor of trampolines and outdoor play equipment that has been operating since 1992. Bounce Pro is the brand name Sportspower uses for many of its trampolines sold through Walmart, Sam's Club, and Costco. The lineup includes round Steelflex Pro trampolines from 8ft to 15ft, a 14ft Garden Style model, oval and square models, smaller \"My First Trampoline\" models for younger kids, and indoor mini trampolines. Pricing is mass-market, typically $150 to $500 depending on size, and warranties commonly run 7 years on the steel frame, 3 years on the mat, and 1 year on other parts. Bounce Pro and Skywalker are direct competitors at the same retailers.",

  JumpKing:
    "JumpKing is one of the oldest names in the US trampoline industry, with roots going back to 1948 and headquarters in Dallas, Texas. The brand was acquired by YJ (USA) Corporation in 2004 and produces a broad range of trampolines including round, rectangular, oval, and multi-level designs from around 7ft up to 17ft, plus accessories and combo packs with basketball hoops and game accessories. Pricing sits in the mid-tier range, typically a few hundred dollars to over a thousand depending on size and features, and the trampolines are sold at Home Depot, Walmart, Amazon, and other major US retailers. JumpKing has historically had a stronger presence in rectangular models than most US mass-market brands.",

  JUMPZYLLA:
    "Jumpzylla is a US-based e-commerce brand founded in 2019 by Michael Bennett, with its first prototype released around 2020. The brand sells round outdoor trampolines from 8ft up to 16ft, with weight capacities listed at 375 lb on smaller sizes and 450 lb on 14ft, 15ft, and 16ft models. Pricing typically falls in the $250 to $500 range on Amazon and the company's own site, with a standard 2-year warranty (extendable to 3 years for an extra fee). The trampolines feature curved enclosure poles, galvanized steel frames, and customizable spring pad colors. Jumpzylla sells direct through its own site, Amazon, and Walmart.",

  ORCC:
    "ORCC is an Amazon-led trampoline brand offering round outdoor trampolines from 8ft to 16ft. Listed weight capacities are typically 375 lb on the 8ft and 10ft models and 400 lb on the 12ft, 14ft, 15ft, and 16ft sizes. The trampolines feature a 6ft enclosure net, foam-padded enclosure poles, hot-dip galvanized frames, and W-shaped legs with U-shaped wind stakes. Pricing sits in the budget tier, generally $200 to $400 depending on size, and ORCC trampolines have passed CPSIA and ASTM F381-16 testing. The brand sells primarily through Amazon and other online retailers.",

  Zupapa:
    "Zupapa is a trampoline brand owned by Maxlead, an e-commerce company that began selling on eBay UK in 2004 and entered the US market in 2005. Zupapa launched its first trampoline in 2011 and now offers round trampolines from 8ft to 16ft, rectangular trampolines from 8x14ft up to 13x23ft, kids rectangles, fitness rebounders, and accessories. Round models typically list weight capacities from 425 lb up to 1,500–1,800 lb total, and rectangular models go up to 2,500 lb. Pricing generally falls in the $400 to $700 range for round models and higher for rectangles, with a standard warranty of 10 years on the frame and 2 years on other components. The brand sells primarily through Amazon and its own site.",

  BCAN:
    "BCAN is a fitness-focused trampoline brand best known for indoor mini rebounders and small outdoor trampolines for older kids. The lineup centers on foldable mini trampolines with handlebars, designed for home cardio workouts, plus a smaller selection of outdoor recreational trampolines. The brand recently became part of FED Fitness. Pricing for mini fitness trampolines generally falls in the $80 to $200 range, with outdoor models priced higher. BCAN sells primarily through Amazon and its own site, with an emphasis on the rebounder fitness category rather than the full backyard trampoline market.",

  Jumpflex:
    "Jumpflex is a New Zealand trampoline brand founded in 2009 by brothers Stephen and Matt Tubbs, and has expanded sales into the USA, UK, Australia, Canada, and Germany. The current lineup is organized into FLEX (entry), HERO (premium), and MEGA (large rectangular) ranges, with sizes from 8ft up to 19ft and total weight ratings up to 550 lb on the larger round models. Pricing in the US sits in the premium tier, generally $1,000 and up, and the brand offers a 10-year warranty on the frame, 5 years on the mat and springs, and 1 year on the net and padding. Jumpflex sells direct through its own US site, with curved enclosure poles and a green-and-black aesthetic across the range.",

  'Upper Bounce':
    "Upper Bounce is part of the Machrus Brands group and is best known in the US trampoline aftermarket for replacement parts (mats, pads, nets, springs, enclosure poles) compatible with multiple brands. The company also sells complete outdoor trampolines from around 7ft up to 16ft (round and rectangular), as well as indoor fitness rebounders. Pricing sits in the budget tier, generally $200 to $600 for complete trampolines, and warranty terms are typically shorter than premium brands. Upper Bounce sells through Amazon, Walmart, Lowe's, and its own sites, with replacement parts being a significant part of the brand's footprint.",

  Springfree:
    "Springfree Trampoline is a New Zealand brand founded by mechanical engineer Dr. Keith Alexander, with the first commercial Springfree released in 2003. The brand sells exclusively springless trampolines, using flexible composite rods beneath the mat instead of metal springs, and offers nine current models across compact round, oval, large round, large oval, large square, jumbo oval, and jumbo square shapes ranging from 6ft up to 12x19ft. Pricing in the US runs from around $1,500 to $4,000 (with bundles approaching $5,000), and all parts carry a 10-year warranty. Springfree sells direct through its own US site, Dick's Sporting Goods, Home Depot, Walmart, and Amazon, plus authorized dealers offering professional installation.",

  ACON:
    "ACON is a Finnish trampoline brand founded in 1996 by Tarmo Sallinen and headquartered in Oulu, Finland. The brand entered the US market in 2014 and offers round trampolines from 6ft to 16ft (the ACON Air series), HD rectangular performance models from 13ft to 16ft, and the high-end ACON X with adjustable spring configuration. Pricing in the US sits firmly in the premium tier, typically $1,150 to $4,000 for standard models, with the ACON X starting at $3,900 and reaching around $10,000 fully loaded. Warranty is 10 years on the frame and 5 years on the mat and springs. ACON also produces hockey training equipment, billiards tables, and other sports equipment, and is distributed in the US through Distributacon Inc.",

  Vuly:
    "Vuly Play is an Australian trampoline brand founded in 2007 by Joe Andon (originally as Trampolines Australia) and headquartered in Brisbane. The brand entered the US market in 2014 through a Toys\"R\"Us distribution deal and a 2015 licensing agreement with Spin Master. Current US lineup includes the Flare, Lift 2, Ultra 2, Thunder 2, and Thunder Pro, with the Thunder series using Vuly's proprietary Leaf Spring system instead of traditional coil springs. Pricing in the US typically runs from around $550 on smaller spring-based models up to $2,400 and beyond for the Thunder series. Vuly also produces basketball hoop systems, modular swing sets (360 Pro), and kids bikes.",

  AGame:
    "AGame is the house trampoline brand of Academy Sports + Outdoors, sold exclusively through Academy stores and Academy.com. The lineup focuses on round backyard trampolines from 7ft up to 16ft, with smaller \"My First\" models for toddlers and combo models with basketball hoops on the larger sizes. Pricing is mass-market, typically $140 to $350, and the trampolines feature galvanized steel frames, UV-resistant jump mats, foam-padded poles, and standard mesh enclosures. Warranty is generally 3 years on the steel frame. AGame is positioned as a value brand for families shopping at Academy and is not sold through other retailers.",

  AlleyOOP:
    "AlleyOOP is the premium trampoline line from JumpSport, the company founded in 1997 by Mark and Valerie Publicover (Mark designed the first commercially successful trampoline safety enclosure). The AlleyOOP range includes VariableBounce, DoubleBounce (a patented two-mat system that softens the impact stage of a bounce), and PowerBounce (which adds a second row of springs) trampolines in round, square, and rectangular shapes from 10ft to 17ft. Pricing in the US starts around $1,500 and reaches several thousand dollars for the larger DoubleBounce and PowerBounce models, with a lifetime frame warranty and an extended Fail-Safe Guarantee on other parts. AlleyOOP sells through its own site, authorized dealers, and select premium retailers.",

  Avyna:
    "Avyna is a Dutch trampoline brand established in 1999 and operated by Tol Outdoor Leisure B.V., headquartered in the Netherlands with manufacturing in its own factory in Vietnam. The brand specializes in above-ground, in-ground, and FlatLevel (fully recessed) trampolines in round and rectangular shapes. In the US (sold as Avyna Pro-Line through trampolines.com and a US distributor), models include 14ft and 15ft rounds and a 10x14ft rectangle, with tested weight capacities listed at over 1,100 lb on in-ground and over 1,300 lb on above-ground models. Pricing in the US sits in the premium tier (typically $2,000 and up), and Avyna offers a lifetime warranty on the frame, 10 years on springs, and 3 years on the mat and pad.",

  Beast:
    "Beast Trampoline is a US brand selling rectangular and round outdoor trampolines, best known for its K9 10x17 Performance Rectangle (with a stated \"no weight limit\" rating), the Amazing Spider 10ft round, and a 14ft round model. The K9 features 9.5-inch piano wire springs, a heavy-duty rectangular frame, and a premium enclosure, and is positioned as a performance trampoline for tricks and athletic use. Pricing typically falls in the upper-mid to premium range depending on model. Beast sells primarily through Amazon and its own site, with a smaller catalog and lower brand awareness than the larger US trampoline brands.",

  'Capital Play':
    "Capital Play is a UK-based brand (Capital Play Worldwide Ltd) specializing in in-ground trampoline kits, with US distribution through Capital Play USA. The lineup includes round in-ground trampolines from 8ft to 14ft and rectangular in-ground models from 8x11ft up to 10x17ft, all built around a bowl-shaped retaining wall design that reduces excavation depth. Models feature TDU vented frame pads, a triple weave vented jump mat, and commercial-grade springs, with a 10-year warranty on the frame and retaining wall, 5 years on the mat and springs, and 2 years on the padding. Pricing typically runs $1,500 to $3,000+ depending on size. Capital Play also distributes the North in-ground trampoline range in partnership with North Trampolines.",

  North:
    "North Trampolines is a Swedish trampoline brand focused on performance and in-ground designs, with a Scandinavian aesthetic and engineering origin. Models include round, oval, and rectangular trampolines such as the Performer Revolution series, with a Horizontal Protection System connecting the mat to the padding, springs that stretch up to twice the length of standard trampoline springs, and the Silence Performance System (SPS) padding above the spring line. In the US, North in-ground trampolines are distributed in collaboration with Capital Play, with current models including 15x10ft and 17x12ft rectangular in-ground kits. Pricing sits in the premium tier (typically $2,500 and up). North trampolines are sold through specialty backyard play system retailers rather than mass-market channels.",

  'Jump Yeti':
    "Jump Yeti is a US trampoline brand sold primarily through Trampolines.com and Amazon, focused on a small lineup of round above-ground trampolines in 12ft, 14ft, and 15ft sizes, with weight capacities listed up to 400 lb. Models feature powder-coated galvanized steel frames, UV-resistant jump mats, foam-padded enclosure poles, and ASTM-certified safety construction. Pricing is positioned at the budget-to-mid end of the market, typically under $500 for the 12ft and 14ft models, with free shipping and a 1-year warranty included. The brand is newer with lower overall recognition compared to legacy mass-market trampoline names.",

  JumpSport:
    "JumpSport is the US trampoline company founded in 1997 by Mark and Valerie Publicover, who designed the first commercially successful trampoline safety net enclosure. The company sells outdoor trampolines under both the JumpSport brand (Classic and Elite series) and the premium AlleyOOP brand, plus indoor fitness rebounders and a wide range of accessories. Outdoor models use proprietary StagedBounce spring technology designed to soften the early stage of a jump, and pricing for full outdoor trampolines typically runs from around $1,000 up to $3,000+ depending on series and size. JumpSport sells direct through its own site and through authorized dealers, with long warranty terms that include a lifetime frame warranty on AlleyOOP models.",

  MaxAir:
    "MaxAir Trampolines is a US manufacturer founded in 2011 and based in Grand Rapids, Michigan, focused on professional-grade and custom super trampolines. The lineup includes square super trampolines (10x10ft, 14x14ft), rectangular models (10x20ft), in-ground installations, and fully custom builds for athletic facilities, trampoline parks, and high-end residential clients. Customers include X Games champions, Olympic medalists, American Ninja Warriors, Hollywood and Broadway stunt teams, and SlamBall (MaxAir partners with the SlamBall League). Pricing sits well above the standard residential market, typically several thousand to tens of thousands of dollars depending on configuration and installation, and the company is a member of IATP and sits on the ASTM International trampoline safety board.",

  'West Coast Jump':
    "West Coast Jump is a family-owned US trampoline manufacturer based in Mesa, Arizona, with a trampoline-making lineage in Mesa dating back to 1979. All trampolines are handcrafted in-house at the Arizona facility, with locally sourced heavy-gauge steel frames and hand-sewn UV-treated textiles. The lineup focuses on rectangular and standard trampolines for residential backyard use, including indoor and outdoor configurations. Pricing sits in the premium tier given the made-in-USA construction, and the brand sells direct rather than through mass-market retailers. West Coast Jump targets buyers specifically looking for American-made backyard trampolines.",

  'Zero Gravity':
    "Zero Gravity Trampolines is a US trampoline brand offering round above-ground trampolines (12ft, 14ft, 15ft) and a 10x17ft Olympic-size rectangular model. Models use TenCate Permatron polypropylene jump mats made in the USA, hot-dip galvanized steel frames with a black powder-coat finish, and 8.5-inch springs on the round models. Pricing typically runs from around $1,100 up to $1,900 depending on size, placing the brand in the upper-mid to premium tier. Zero Gravity trampolines are sold through specialty backyard and play system retailers (such as Beyond Backyards and Tree Frogs) rather than mass-market online channels, often with optional installation included.",
};
